---
resources:
- name: go-library-source
  type: git
  source:
    uri: https://github.com/christopherneuhardt/12FactorGoLibrary
    branch: master

- name: library-deploy-test
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

- name: library-deploy-prod
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
    
jobs:
- name: deploy-test
  serial: true
  plan:
  - get: go-library-source
    trigger: true
  - task: build-deploy-go-library
    file: go-library-source/src/12FactorGoLibrary/ci/build.yml
    privileged: true
  - put: library-deploy-test
    params:
       manifest: go-library-source/src/12FactorGoLibrary/manifest.yml
       path: go-library-source/src/12FactorGoLibrary
- name: deploy-prod
  serial: true
  plan:
  - get: go-library-source
    passed: [ deploy-test ]
    trigger: false
  - task: build-deploy-go-library
    file: go-library-source/src/12FactorGoLibrary/ci/build.yml
    privileged: true
  - put: library-deploy-prod
    params:
       manifest: go-library-source/src/12FactorGoLibrary/manifest.yml
       path: go-library-source/src/12FactorGoLibrary
